New sprint PR
SouJunior/mentores-backend pull request #23
Opened 2023-07-17 03:35 UTC by PatrickOtero

A basic and functional version of the testimony module was created, the confirmEmail.hbs file was updated with the new template provided by the frontend and an useless test file named "user.repository.spec.ts" was deleted.

2023-07-19 12:55 UTC, wandersonDeve requested changes

2023-07-19 12:55 UTC, wandersonDeve commented on src/templates/confirmEmail.hbs
> +								Para confirmar o e-mail meuemail@mail.com e concluir o seu cadastro, clique no botão abaixo:
Remover o 'meuemail@mail.com' e adicionar o email da pessal

2023-07-19 12:55 UTC, wandersonDeve commented on src/templates/confirmEmail.hbs
> +							<a href="https://mentoria-online.vercel.app/confirmacao?code=${code}&email=${encodedEmail}" target="_blank" style="font-size: 16px; font-weight: 400; font-family: 'Radio Canada', sans-serif; b
O valor 'https://mentoria-online.vercel.app/confirmacao?' esta no .env da aplicação, por esse morivo ele nao precisa ficar aqui chapado, deixa ele no service do modulo mail, assim caso o front mude fica mais facil fazer essa mudança

2023-07-19 12:55 UTC, wandersonDeve commented on src/templates/confirmEmail.hbs
> +							<h2 style="margin: 28px 0px 16px; font-size: 24px; font-weight: 700;">Seja bem-vindo!</h2>
antes era '<h2>Seja bem-vindo {{name}}!</h2>', porem nao vi a mudança no service no mail, pois se o campo name esta sendo passo e nao goi adicionado aqui vai quebrar na hora do envio.

2023-07-22 13:54 UTC, PatrickOtero commented on src/templates/confirmEmail.hbs
> +								Para confirmar o e-mail meuemail@mail.com e concluir o seu cadastro, clique no botão abaixo:
Feito

2023-07-22 13:54 UTC, PatrickOtero commented on src/templates/confirmEmail.hbs
> +							<h2 style="margin: 28px 0px 16px; font-size: 24px; font-weight: 700;">Seja bem-vindo!</h2>
Feito

2023-07-22 13:54 UTC, PatrickOtero commented on src/templates/confirmEmail.hbs
> +							<a href="https://mentoria-online.vercel.app/confirmacao?code=${code}&email=${encodedEmail}" target="_blank" style="font-size: 16px; font-weight: 400; font-family: 'Radio Canada', sans-serif; b
Feito

2023-07-23 17:07 UTC, wandersonDeve approved these changes

2023-07-23 17:07 UTC, merged